CREATE TABLE KIT (
	ID_KIT		INT IDENTITY NOT NULL,
	ACESSORIO1  VARCHAR (50) NULL,
	ACESSORIO2  VARCHAR (50) NULL,
	ACESSORIO3  VARCHAR (50) NULL,
	ACESSORIO4  VARCHAR (50) NULL,
	ACESSORIO5  VARCHAR (50) NULL,
	CONSTRAINT PK_KIT PRIMARY KEY (ID_KIT)
)


CREATE TABLE VEICULO (
	ID_VEICULO	INT PRIMARY KEY IDENTITY,
	MODELO				VARCHAR (40),
	ANO					VARCHAR (5),
	COR					VARCHAR (40),
	MOTOR				VARCHAR (50),
	MONTADORA			VARCHAR (50),
	CATEGORIA			VARCHAR (40),
	PRECO				VARCHAR (15),
	IMAGEM				VARCHAR (255)
);

CREATE TABLE CONCESSIONARIA (
	ID_CONCESSIONARIA	INT IDENTITY (1,1) NOT NULL,
	CNPJ				VARCHAR (15) NOT NULL,
	NOME_FANTASIA		VARCHAR (50) NOT NULL,
	RAZAO_SOCIAL		VARCHAR (50) NOT NULL,
	CONSTRAINT PK_CON	PRIMARY KEY (ID_CONCESSIONARIA) 
)

CREATE TABLE PEDIDO (
	ID_PEDIDO	INT PRIMARY KEY IDENTITY,
	DATA_PEDIDO			VARCHAR (12),
	STATUS_PEDIDO		VARCHAR (15),
	VALOR_PEDIDO		VARCHAR (10),
	ID_VEICULO		VARCHAR (40),
	ID_KIT				VARCHAR (5),
	ID_INTERESSADO		VARCHAR (5),	
	ID_CONCESSIONARIA1	INT,
	ID_CONCESSIONARIA2	INT,
	ID_CONCESSIONARIA3	INT	
);

CREATE TABLE INTERESSADO (
	ID_INTERESSADO	INT PRIMARY KEY IDENTITY,
	NOME			CHAR (70),
	RG				CHAR (15),
	CPF				CHAR (15),
	NASCIMENTO		CHAR (12),
	SEXO			CHAR (10),
);
	
CREATE TABLE ENDERECO (
	ID_ENDERECO		INT PRIMARY KEY IDENTITY,
	ESTADO			CHAR (40),
	CIDADE			CHAR (40),
	BAIRRO			CHAR (40),
	LAGRADOURO		CHAR (50),
	CEP				CHAR (12),
	NUMERO			CHAR (10),
	COMPLEMENTO		CHAR (30),
	ID_INTERESSADO	INT NULL,

	CONSTRAINT FK_INTERESSADO_ID_INTERESSADO
	FOREIGN KEY (ID_INTERESSADO) REFERENCES INTERESSADO(ID_INTERESSADO)
	ON DELETE CASCADE, 
);

CREATE TABLE CONTATO (
	ID_CONTATO		INT PRIMARY KEY IDENTITY,
	EMAIL			CHAR (50),
	TELEFONE		CHAR (15),
	TELEFONE2		CHAR (15),
	CELULAR			CHAR (15),
	FAX				CHAR (15),
	ID_INTERESSADO	INT NULL,

	CONSTRAINT FK_INTERES_ID_INTERESSADO
	FOREIGN KEY (ID_INTERESSADO) REFERENCES INTERESSADO(ID_INTERESSADO)
	ON DELETE CASCADE, 
);


CREATE TABLE USUARIO (
ID_USUARIO INT IDENTITY NOT NULL,
NOME        VARCHAR (255) NULL,
USUARIO     VARCHAR (100) NOT NULL,
SENHA       VARCHAR (100) NOT NULL,
NIVEL       VARCHAR (50) NOT NULL,
CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)

)

